dependencies {
    implementation project(':common:common-domain')

    implementation 'org.springframework.cloud:spring-cloud-starter-config'
//    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.axonframework:axon-spring-boot-starter:4.13.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'

    // depedencies of mudule :
    implementation project(':microservices:gateway-service:gateway-application:gateway-restapi')
    implementation project(':microservices:gateway-service:gateway-datapersistence')
    implementation project(':microservices:gateway-service:gateway-message')
    implementation project(':microservices:gateway-service:gateway-domain:gateway-application-service')
    implementation project(':microservices:gateway-service:gateway-domain:gateway-domain-core')
    implementation project(':microservices:gateway-service:gateway-infrastructure')


}
