server:
  port: 16901

stadoor:
  frontend:
    public-origin: https://authgate.site
    gateway-origin: https://authgate.site
    iam-origin: https://authgate.site
  security:
    issuer-uri: https://iam.authgate.site
    logout-origin: https://iam.authgate.site

spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            websocket:
              max-frame-payload-length: 10485760
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: iam-pat-api
              uri: https://iam.authgate.site
              order: -1
              predicates:
                - Path=/api/front/pat/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/pat(?<segment>/?.*), /api/v1/iam/pat${segment}

            - id: iam-tenant-api
              uri: https://iam.authgate.site
              order: -1
              predicates:
                - Path=/api/front/tenants/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/tenants(?<segment>/?.*), /api/v1/iam/tenants${segment}

            - id: gateway-service-gateways-api
              uri: http://authgate-gateway-service:16803
              order: -1
              predicates:
                - Path=/api/front/gateways/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/gateways(?<segment>/?.*), /api/v1/gateways${segment}

            - id: gateway-service-services-api
              uri: http://authgate-gateway-service:16803
              order: -1
              predicates:
                - Path=/api/front/services/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/services(?<segment>/?.*), /api/v1/services${segment}

            - id: gateway-service-routes-api
              uri: http://authgate-gateway-service:16803
              order: -1
              predicates:
                - Path=/api/front/routes/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/routes(?<segment>/?.*), /api/v1/routes${segment}

            - id: consumer-service-api
              uri: http://consumer-service:16804
              order: -1
              predicates:
                - Path=/api/front/consumers/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/consumers(?<segment>/?.*), /api/v1/consumers${segment}

            - id: iam-service-api
              uri: https://iam.authgate.site
              predicates:
                - Path=/api/front/**
              filters:
                - TokenRelay=
                - SaveSession=
                - RewritePath=/api/front/(?<segment>.*), /api/v1/iam/${segment}

            - id: public-ui
              uri: http://authgate-public-app:3000
              predicates:
                - Path=/**

  security:
    oauth2:
      client:
        provider:
          stadoor:
            issuer-uri: ${stadoor.security.issuer-uri}
        registration:
          stadoor:
            provider: stadoor
            client-id: stadoor
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "https://api.authgate.site/login/oauth2/code/stadoor"
            scope:
              - openid
              - profile
              - email
              - offline_access

eureka:
  client:
    service-url:
      defaultZone: http://authgate-eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: INFO
