dependencies {
	implementation project(':common:common-domain')

	implementation project(':microservices:gateway-service:gateway-domain:gateway-application-service')

	implementation 'org.springframework.boot:spring-boot-starter-webclient'
	implementation 'org.springframework.cloud:spring-cloud-starter-config'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'


}