dependencies {
    implementation project(':microservices:gateway-service:gateway-domain:gateway-application-service')
    implementation project(':microservices:gateway-service:gateway-domain:gateway-domain-core')


    implementation 'org.axonframework.extensions.kafka:axon-kafka-spring-boot-starter:4.12.0'
    implementation 'org.axonframework:axon-spring-boot-starter:4.13.0'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}
