server:
  port: 16803

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://iam.authgate.site

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://authgate-gateway:5432/gateway_db
    username: authgate_gateway
    password: ${DB_PASSWORD}

  r2dbc:
    url: r2dbc:postgresql://authgate-gateway:5432/gateway_db
    username: authgate_gateway
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://authgate-gateway:5432/gateway_db
    user: authgate_gateway
    password: ${DB_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: kafka-broker-1:9090,kafka-broker-2:9090,kafka-broker-3:9090
    default-topic: gateway.events.v1
    publisher:
      enabled: true
    fetcher:
      enabled: false
  serializer:
    general: jackson
    events: jackson
    messages: jackson

eureka:
  client:
    service-url:
      defaultZone: http://authgate-eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    kh.edu.istad.stadoor.gateway: INFO
