plugins {
    id 'application'
}

dependencies {
    implementation 'info.picocli:picocli:4.7.7'
    annotationProcessor 'info.picocli:picocli-codegen:4.7.7'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}

application {
    mainClass = 'kh.edu.istad.stadoor.cli.StadoorCli'
}

bootJar {
    enabled = true
    archiveFileName = 'stadoor-cli.jar'
    mainClass = 'kh.edu.istad.stadoor.cli.StadoorCli'
}

jar {
    enabled = true
}
