services:
  stadoor-user-profile:
    image: mongo:7
    container_name: stadoor-user-profile
    ports:
      - "16702:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: stadoor
      MONGO_INITDB_ROOT_PASSWORD: stadoor
    volumes:
      - mongodb_log:/var/log/mongodb
      - stadoor_user_profile_data:/data/db
    networks:
      - stadoor-net
volumes:
  stadoor_user_profile_data:
  mongodb_log:

networks:
  stadoor-net:
    external: true