bind 0.0.0.0
protected-mode no
port 6379
requirepass authgate@168
databases 1
save ""
appendonly no
maxmemory 256mb
maxmemory-policy allkeys-lru
maxmemory-samples 5
tcp-keepalive 60
timeout 0
dir /data