server:
  port: 16903

spring:
  data:
    redis:
      host: ${INFRA_HOST}
      port: 16712
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:16801
          jwk-set-uri: http://localhost:16801/oauth2/jwks

stadoor:
  clients:
    gateway-service:
      base-url: http://localhost:16803
    iam:
      base-url: http://localhost:16801
    consumer:
      base-url: http://localhost:16804

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
