server:
  port: 16805

spring:
  kafka:
    bootstrap-servers: kafka-broker-1:9090,kafka-broker-2:9090,kafka-broker-3:9090
    consumer:
      group-id: eureka-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "kh.edu.istad.stdoor.eureka.event"
        spring.json.value.default.type: kh.edu.istad.stdoor.eureka.event.ServiceInstanceCreatedEvent
        spring.json.use.type.headers: false

  mongodb:
    uri: mongodb://authgate:${MONGO_PASSWORD}@authgate-eureka-db:27017/eureka_server_db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://authgate-eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false

eureka-api:
  base-url: http://authgate-eureka-server:8761/eureka/v2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
