dependencies {
    implementation project(':microservices:consumer-service:consumer-domain:consumer-domain-core')
    implementation 'org.springframework:spring-tx'
    implementation 'org.axonframework:axon-spring-boot-starter:4.13.0'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}
